Domain/customer
realponto-project/realponto-core pull request #36
Opened 2021-03-08 20:09 UTC by jessiLeandro

## Contexto
Foi criado o domain eos testes de customer e address.

## Checklist
- [ ]  Criar domain
- [ ]  Criar Test

## Issues linkadas
- [ ] Resolves #16 

## Notas de deploy
O banco de dados deve estar limpo.

## Como testar?

1. Baxiar a branch `domanin/customer`.
2. Execute `docker-compose up`, na raiz do projeto para rodar o banco de teste e de desenvolvimento.
3. Execute `yarn test`, na raiz do projeto para rodar os tests altomatizados.

**Novos scripts**:

- `test` :  executa os testses automatizados, a opção `--watch` pode ajuda. 

**Novas dependências**:

- `dependency` : detalhes da dependência

**Novas dependências de desenvolvedor**:

- `jest` :  Lib para creiar e executar teste automatizados.
- `faker` : Lib para gerar dados fake.
-  `yup` :  Lib para validações.
-  `@fnando/cnpj` : Lib para lidar com cpnj ( validação, gerador )

2021-03-09 16:19 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    const costumerMock = generatorFakerCustomer()
```suggestion
    const custumerMock = generatorFakerCustomer()
```

2021-03-09 16:20 UTC, guilhermestain commented on domains/Customer/index.test.js
> +      ...costumerMock,
```suggestion
      ...customerMock,
```

2021-03-09 16:20 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerCreated).toHaveProperty('name', costumerMock.name)
```suggestion
    expect(customerCreated).toHaveProperty('name', customerMock.name)
```

2021-03-09 16:21 UTC, guilhermestain commented on domains/Customer/index.test.js
> +      costumerMock.socialName
```suggestion
      customerMock.socialName
```

2021-03-09 16:21 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerCreated).toHaveProperty('document', costumerMock.document)
```suggestion
    expect(customerCreated).toHaveProperty('document',   customerMock.document)
```

2021-03-09 16:21 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerCreated).toHaveProperty('phone', costumerMock.phone)
```suggestion
    expect(customerCreated).toHaveProperty('phone',  customerMock.phone)
```

2021-03-09 16:22 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    const costumerMock = generatorFakerCustomer()
```suggestion
    const  customerMock = generatorFakerCustomer()
```

2021-03-09 16:22 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerupdated).toHaveProperty('name', costumerMock.name)
```suggestion
    expect(customerupdated).toHaveProperty('name',  customerMock.name)
```

2021-03-09 16:22 UTC, guilhermestain commented on domains/Customer/index.test.js
> +      costumerMock.socialName
```suggestion
       customerMock.socialName
```

2021-03-09 16:23 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerupdated).toHaveProperty('document', costumerMock.document)
```suggestion
    expect(customerupdated).toHaveProperty('document',  customerMock.document)
```

2021-03-09 16:23 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    const costumerMock = generatorFakerCustomer()
```suggestion
    const  customerMock = generatorFakerCustomer()
```

2021-03-09 16:23 UTC, guilhermestain commented on domains/Customer/index.test.js
> +        ...costumerMock,
```suggestion
        ... customerMock,
```

2021-03-09 16:23 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerupdated).toHaveProperty('name', costumerMock.name)
```suggestion
    expect(customerupdated).toHaveProperty('name',  customerMock.name)
```

2021-03-09 16:23 UTC, guilhermestain commented on domains/Customer/index.test.js
> +      costumerMock.socialName
```suggestion
       customerMock.socialName
```

2021-03-09 16:24 UTC, guilhermestain commented on domains/Customer/index.test.js
> +    expect(customerupdated).toHaveProperty('phone', costumerMock.phone)
```suggestion
    expect(customerupdated).toHaveProperty('phone',  customerMock.phone)
```

2021-03-10 11:11 UTC, novarealponto requested changes

2021-03-10 11:11 UTC, novarealponto commented on domains/Address/index.test.js
> +
os valores dos preços é int mesmo não iremos usar float por conta dos numeros mágicos do javascript, iremos passar valores em milhares, exemplo 100 = 1,00 1000 = 10,00 12345 = 123.45 iremos usar esse modelo de numero para os preçosfalta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Address/index.test.js
> +  })
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Address/index.test.js
> +  })
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Customer/index.test.js
> +  })
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Customer/index.test.js
> +    expect(customerCreated).toHaveProperty('companyId', companyId)
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Customer/index.test.js
> +  })
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/Customer/index.test.js
> +    )
falta testar os valores que foi inserido não apenas se existe props, não devemos usar o valor do mock para comparar devemos escrever de form explicita

2021-03-10 11:11 UTC, novarealponto commented on domains/Customer/index.test.js
> +    expect(customerFinded.address).toStrictEqual(customer.address)
mesmo comentario do de cima

2021-03-10 11:11 UTC, novarealponto commented on domains/status/index.test.js
> +  })
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/status/index.test.js
> +    )
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on domains/status/index.test.js
> +    expect(getStatusById).toHaveProperty(
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:11 UTC, novarealponto commented on package.json
> +    "jest": "^26.6.3",
devemos travar as dependencias removendo ^

2021-03-10 19:10 UTC, jessiLeandro commented on domains/Address/index.test.js
> +
não entendo a relação do comentário com o código em questão

2021-03-11 17:42 UTC, jessiLeandro commented on package.json
> +    "jest": "^26.6.3",
vamos travar a versão de todas as dependências?

2021-03-15 13:58 UTC, merged