Domain/product
realponto-project/realponto-core pull request #38
Opened 2021-03-09 14:01 UTC by guilhermestain

## Contexto
Foi criado o domain e testes para produtos.

## Checklist
- [ ] Criar domain.
- [ ]  Criar Test.

## Issues linkadas
- [ ] Resolves #14  

## Como testar?

1. Baxiar a branch `domanin/product`.
2. Execute `docker-compose up`, na raiz do projeto para rodar o banco de teste e de desenvolvimento.
3. Execute `yarn test`, na raiz do projeto para rodar os tests altomatizados

**Novos scripts**:

- `test` : executa os testses automatizados, a opção `--watch` pode ajuda.

**Novas dependências**:

- `yup` : Lib para validações.
- `dotenv`: Lib para lidar com variáeis ambiente

**Novas dependências de desenvolvedor**:

- `jest` : Lib para creiar e executar teste automatizados.
- `faker` : Lib para gerar dados fake.

2021-03-09 17:27 UTC, jessiLeandro commented on domain/product/index.test.js
> +    expect(true).toBeTruthy()
verificação desnecessária

2021-03-09 19:38 UTC, jessiLeandro commented on domain/product/index.js
> +const productSchema = require('../../utils/helpers/Schemas/product')
separar importações das declarações

2021-03-09 19:38 UTC, jessiLeandro commented on domain/product/index.test.js
> +const { ValidationError } = require('sequelize')
organizar as importações,  (primeiro as node depois as da suas)

2021-03-09 19:38 UTC, jessiLeandro approved these changes

2021-03-10 11:07 UTC, novarealponto requested changes

2021-03-10 11:07 UTC, novarealponto commented on database/migrations/20210105124948-product.js
> +        type: Sequelize.FLOAT,
os valores dos preços é int mesmo não iremos usar float por conta dos numeros mágicos do javascript, iremos passar valores em milhares, exemplo 100 = 1,00   1000 = 10,00 12345 = 123.45 iremos usar esse modelo de numero para os preços

2021-03-10 11:07 UTC, novarealponto commented on database/models/product.model.js
> +      type: Sequelize.FLOAT,
os valores dos preços é int mesmo não iremos usar float por conta dos numeros mágicos do javascript, iremos passar valores em milhares, exemplo 100 = 1,00 1000 = 10,00 12345 = 123.45 iremos usar esse modelo de numero para os preços

2021-03-10 11:07 UTC, novarealponto commented on domain/product/index.test.js
> +    expect(productCreated).toHaveProperty('companyId')
falta testar os valores que foi inserido não apenas se existe props

2021-03-10 11:07 UTC, novarealponto commented on domain/product/index.test.js
> +  })
não devemos comparar o retorno usando o mock devemos escrever os valores para garatirmos que vai da certo

2021-03-12 13:19 UTC, jessiLeandro approved these changes

2021-03-12 13:19 UTC, merged